### ISSUE TITLE
Does work on Voice File

### ISSUE THREAD

**Issue by ParameterT** [Surihix/Drakengard3xxxToMp3#1]
Thanks for your work, it works on BGM and MUSIC but it does not work on voice file (.XXX file start with VO_).
Do you know how to extract those voice files?
Another tool i used "umodel" shows "Wrong package tag (42444553) in file. Probably the file is encrypted."

**Comment by ParameterT** [comment]
Never mind, just found out rename it to .mp3 will do.

**Comment by Surihix** [comment]
> Never mind, just found out rename it to .mp3 will do.

Can you post that VO file here ?
I will take a look at see what is causing my tool to screw up and see if it can be addressed.

**Comment by Surihix** [comment]
Found an issue with the way the necessary offsets required for extraction is determined. will be fixing this currently.

**Comment by Surihix** [comment]
fixed this issue properly in version 1.2.
